version: "3.4"
services:
  postgresql:
    image: postgres:11.5
    container_name: zc-postgres
    hostname: zc-postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: db

  redis:
    image: redis
    container_name: zc-redis
    hostname: zc-redis
    command: redis-server --appendonly yes
    ports:
      - 6379:6379
    volumes:
      - ./data/redis:/data

  maildev:
    image: maildev/maildev
    container_name: zc-maildev
    hostname: zc-maildev
    ports:
      - "1025:25"
      - "1080:80"

  api:
    container_name: zc-api
    hostname: zc-api
    ports:
      - 3000:3000
    volumes:
      - ./data/avatars:/app/avatars
      - ./data/certs:/certs:ro
    command: sh -c "
      yarn wait-on tcp:zc-postgres:5432 &&
      yarn db:migrate &&
      node src/modules/seed &&
      node src/main.js"
    environment:
      LISTEN_PORT: 3000
      LISTEN_IP: 0.0.0.0
      LOG_LEVEL: log
      TRUST_PROXY: "true"
      REFLECT_ORIGIN: "true"
      ADMIN_USER: admin:admin@zetecom.fr:admin42
      APP_URL: http://${LOCAL_IP:-localhost}:8000
      WEBSITE_URL: http://${LOCAL_IP:-localhost}:8080
      DB_HOST: zc-postgres
      DB_PORT: 5432
      DB_USER: root
      DB_PASS: root
      DB_NAME: db
      DB_NAME_ROOT: postgres
      DB_ENTITIES: src/**/*.entity.js
      DB_MIGRATIONS: migrations/*.js
      DB_SEEDS: seeds/*.js
      REDIS_HOST: zc-redis
      REDIS_PORT: 6379
      EMAIL_HOST: zc-maildev
      EMAIL_PORT: 25
      EMAIL_USER: username
      EMAIL_PASSWORD: password
      EMAIL_SECURE: "false"
      EMAIL_BYPASS: "false"
      EMAIL_ACCOUNT_VERIFICATION: "true"
      EMAIL_FROM: "Zétécom <contact@zetecom.fr>"
      SESSION_SECRET: sekret
      SECURE_COOKIE: "false"
      USER_AVATAR_DESTINATION: /app/avatars
